name: Build and Push Docker Image

on:
  push:
    branches:
      - main # You can specify the branch you want to trigger this workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t sadafshaikh/dockimg:latest .
        

      - name: Push Docker image to Docker Hub
        run: docker push sadafshaikh/dockimg:latest
